### ISSUE TITLE
PF2, Cone Templates have a bugged square

### ISSUE THREAD

**Issue by apoapostolov** [BoltsJ/grid-aware-templates#1]
The Grid Aware templates need to support PF2 cones, perhaps as a system recognition. See below the official cone images. Also I noticed a bugged square moved to a wrong position. 

![image](https://user-images.githubusercontent.com/4083812/197170081-d70fa4e4-8374-462f-a85b-403ddb23c331.png)

Similar problem with Large Auras

![image](https://user-images.githubusercontent.com/4083812/197170859-faeba0f9-7509-4a74-aaf9-ae63967cdf27.png)

The PF2 templates for reference, if needed:

![image](https://user-images.githubusercontent.com/4083812/197170224-d68e8d33-4baa-4756-8f8e-39840276b1c4.png)

**Comment by BoltsJ** [comment]
I didn't look into pf2e square grids too much, but doesn't pf2e already override the template shapes for square grids? It seemed like that was the case when I was testing.

**Comment by apoapostolov** [comment]
Yes you're right. I don't need this for PF2. Feel free to close this issue, I will open new one if I can reproduce the rogue squares in 5E.
