### ISSUE TITLE
[DND] Critical Conflict with Drag Ruler

### ISSUE THREAD

**Issue by apoapostolov** [BoltsJ/grid-aware-templates#5]
5E latest, Grid Aware v3 , Drag Ruler 1.13.2

Causes templates to never be dropped when dragged, bricking the environment until refresh. Cannot move templates at all. 

![image](https://user-images.githubusercontent.com/4083812/206875550-03aaa0cc-2680-494b-a036-bfd839480b6b.png)

**Comment by BoltsJ** [comment]
Sorry for the delay, but I finally got some time to work on stuff. However, I can't replicate this. I do get warnings about compatibility, but it doesn't break. Can you try manually changing the priority of this module and drag-ruler in the libwrapper menu?

**Comment by BoltsJ** [comment]
Also, instinctually, I'm not sure that drag ruler should be using a mixed/override wrapper for the conflicting method. It seems like the reason for the override should be manageable from a WRAPPER override.
